### ISSUE TITLE
$db her zaman null

### ISSUE THREAD

**Issue by Orkuncakilkaya** [csrrmzn/depo-yonetimi#1]
https://github.com/csrrmzn/depo-yonetimi/blob/591249e75d89db895359896b6875fa91ee389de1/Lib/DbConnect.php#L15

TryCatch dışında db değişkenine null ataması yapmışsın. Bu try ve catch sonuçları ne olursa olsun bu atamayı her zaman yapar. db değişkenini dışarıda kullanmayı planlıyorsan bu satırı TryCatch bloklarının üstüne taşı.

**Comment by csrrmzn** [comment]
Uyarınız için teşekkür ederim hocam. Database işlemlerini class olarak düzenledim.

**Comment by Orkuncakilkaya** [comment]
https://github.com/csrrmzn/depo-yonetimi/blob/591249e75d89db895359896b6875fa91ee389de1/Lib/DbConnect.php#L15
Bu dosyaya ihtiyacın yoksa kaldırabilirsin o zaman. Bu Issue'yu tamamlandığını düşünüyorsan Closed'a çekmeyi unutma :)
